version: "3"
services:

  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: eclinc
      POSTGRES_DB: eclinc
    ports:
      - 5436:5432
    volumes:
      - ./postgres-data:/bitnami/postgresql/data

# codigo para rodar em qlqr maquina
# docker-compose up -d